### ISSUE TITLE
Here’s a modified version that works in Minecraft 1.21.4.

### ISSUE THREAD

**Issue by Mateocchi** [TheAdorableCat/VanilLog#6]
[vanilog.zip](https://github.com/user-attachments/files/18230851/vanilog.zip)
Just a few small changes were made to ensure it works directly in 1.21.4 without requiring anything else beyond installation.

**Comment by TheAdorableCat** [comment]
thank you for that I'll make sure to zip the releases better to be used as is going forward.

**Comment by Mateocchi** [comment]
Np, thx u for the datapack

**Comment by TheAdorableCat** [comment]
fixed this in 1.4.2
